use_frameworks!

target 'CAUMengSocial_Example' do
  pod 'CAUMengSocial', :path => '../'

  target 'CAUMengSocial_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
